Proximity-aware screen lock [WIP]
Trying something new this time.
The idea is to check the proximity sensor value while the button
is pressed (to conserve battery power), and if the proximity
sensor reports "NEAR" (the sensor is blocked) - light up the red
LED (thus, letting the user know this, if he covered the sensor
accidentally) instead of waking the device.

*** THIS DOES NOT EVEN BUILD YET ***

frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:5550:
error: cannot find symbol
mSensorManager = (SensorManager) getSystemService(SENSOR_SERVICE);
                                                  ^
  symbol:   variable SENSOR_SERVICE
  location: class PhoneWindowManager.ProximityLock

frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:5568:
error: non-static method getSystemService(String) cannot be referenced from a static context
NotificationManager notifMgr = (NotificationManager)Context.getSystemService(Context.NOTIFICATION_SERVICE);
                                                           ^

Help on making it compile will be much appreciated :)

Change-Id: I750cdd9afc581d41b94b253438a6b6b44337c0fa