SystemUI: Check if a task's group is null prior to checking if its the front most task.
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
    com.android.systemui.recents.model.TaskGrouping.isFrontMostTask(com.android.systemui.recents.model.Task)' on a null object reference
      at com.android.systemui.recents.views.RecentsView.onTaskViewClicked(RecentsView.java:535)
      at com.android.systemui.recents.views.TaskStackView.onTaskViewClicked(TaskStackView.java:1125)
      at com.android.systemui.recents.views.TaskView.onClick(TaskView.java:881)
      at android.view.View.performClick(View.java:4756)
      at android.view.View$PerformClick.run(View.java:19749)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)

Change-Id: I04afec21a7c4e7ba5b3e51ae76a2065e98e6cfa2